version: '3.9'

services:

  mysql:
    image: mysql:8
    container_name: multimedia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: multimedia_processing
      MYSQL_USER: multimedia_user
      MYSQL_PASSWORD: multimedia_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - multimedia-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: multimedia-rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - multimedia-network

  minio:
    image: minio/minio
    container_name: multimedia-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - multimedia-network


  thumbnail-worker:
    build:
      context: ./workers/thumbnail-worker

    container_name: thumbnail-worker

    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

    environment:
      RABBITMQ_HOST: rabbitmq

      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

      MINIO_BUCKET: uploads

    networks:
      - multimedia-network


  audio-worker:
    build:
      context: ./workers/audio-worker

    container_name: audio-worker

    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

    environment:
      RABBITMQ_HOST: rabbitmq

      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

      MINIO_BUCKET: uploads

    networks:
      - multimedia-network


  transcode-worker:
    build:
      context: ./workers/transcode-worker

    container_name: transcode-worker

    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

    environment:
      RABBITMQ_HOST: rabbitmq

      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

      MINIO_BUCKET: uploads

    networks:
      - multimedia-network

volumes:
  mysql_data:
  minio_data:


networks:
  multimedia-network: